tiles = {
            1: 'spring_grass.png',
            2: 'rock.png',
            3: 'spring_dirt.png',
            4: 'spring_burrow.png',
            5: 'spring_water_flow.gif',
            6: 'spring_flower_grass.gif',
            7: 'mud.png',
            8: 'night_grass.png',
            9: 'night_fireflies.png',
            10: 'summer_grass.png',
            11: 'summer_dirt.png',
            12: 'summer_burrow.png',
            13: 'night_dirt.png',
            14: 'night_burrow.png',
            15: 'summer_bugs_grass.png',
            16: 'summer_water_flow.png',
            17: 'fall_grass.png',
            18: '',
            19: 'night_grass.png',
            20: 'fall_leaves_grass.png',
            21: '',
            22: '',
            23: 'summer_dirt.png',
            24: 'summer_burrow.png',
            25: 'water.png',
            26: 'summer_water_N.png',
            27: 'summer_water_S.png',
            28: 'summer_water_W.png',
            29: 'summer_water_E.png',
            30: 'summer_water_NE.png',
            31: 'summer_water_NW.png',
            32: 'summer_water_SE.png',
            33: 'fall_dirt.png',
            34: 'fall_burrow.png',
            35: 'summer_water_SW.png',
            36: 'winter_grass.png',
            37: 'winter_hole.png',
            38: 'winter_hole_filled.png',
            39: 'winter_roots_grass.png',
            40: 'black.png',
            41: 'tiles.png'

        }

items = {
            0: 'transparent.png',
            1: 'summer_fruit.png',
            2: 'carrot.png',
            3: 'marker.png',
            4: 'night_trees.png',
            5: 'boulder.png',
            6: 'log_half1_horizontal.png',
            7: 'log_half2_horizontal.png',
            8: 'log_half1_vertical.png',
            9: 'log_half2_vertical.png',
            10: 'mysterious_door_half1.png',
            11: 'mysterious_door_half2.png',
            12: 'spring_door.png',
            13: 'fence_front.png',
            14: 'fence_side.png',
            15: 'spring_bush.png',
            16: 'summer_door.png',
            17: 'summer_bush.png',
            18: 'fall_bush2.png',
            19: 'fall_fruit.png',
            20: 'letter_L.png',
            21: 'letter_A.png',
            22: 'letter_R.png',
            23: 'letter_A.png',
            24: 'empty_letter.png',
            25: 'snowball.png',
            26: 'fall_door.png',
            27: 'winter_door.png',
            28: 'winter_bush.png',
            29: 'mysterious_door_half1_open.png',
            30: 'mysterious_door_half2_open.png',
        }

eatable = [1, 6, 8, 9, 10, 15, 17, 20]
diggable = []
hole = [4, 14, 24, 34]
warpable = [3, 4, 13, 14, 23, 24, 33, 34]
unpassable = [5, 16, 19, 25, 26, 27, 28, 29, 30, 31, 32, 37]
slippery = [7]
fillable = [37]

blocked_items = [4, 5, 6, 7, 8, 9, 10, 13, 14, 15, 17, 18, 20, 21, 22, 23, 24, 28]

level_list = [
    'levels/night_1.lvl',
    'levels/night_2.lvl',
    'levels/night_3.lvl',
    'levels/night_4.lvl',
    'levels/night_5.lvl',
    'levels/lobby.lvl',
    'levels/spring_1.lvl',
    'levels/spring_2.lvl',
    'levels/spring_3.lvl',
    'levels/spring_4.lvl',
    'levels/spring_5.lvl',
    'levels/summer_1.lvl',
    'levels/summer_2.lvl',
    'levels/summer_3.lvl',
    'levels/summer_4.lvl',
    'levels/summer_5.lvl',
    'levels/fall_1.lvl',
    'levels/fall_2.lvl',
    'levels/fall_3.lvl',
    'levels/fall_4.lvl',
    'levels/fall_5.lvl',
    'levels/winter_1.lvl',
    'levels/winter_2.lvl',
    'levels/winter_3.lvl',
    'levels/winter_4.lvl',
    'levels/winter_5.lvl',
    'levels/end.lvl'
]

music_list = ["spring.mp3", "night.mp3"]